steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/prj-se-madkumar4-b082/my-function-image'
      - '.'

images:
  - 'gcr.io/prj-se-madkumar4-b082/my-function-image'
